#!/usr/bin/env python
# eg_manta 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# See https://documentation.dnanexus.com/developer for documentation and
# tutorials on how to modify this file.
#
# DNAnexus Python Bindings (dxpy) documentation:
#   http://autodoc.dnanexus.com/bindings/python/current/

import dxpy
import glob
import os
import stat
import subprocess

@dxpy.entry_point('main')
def main(bams, family_number, sample_number):
    # give permission to run shell script
    os.chmod("/home/dnanexus/run_manta.sh", stat.S_IRWXU | stat.S_IRWXG | stat.S_IXOTH)

    # The following line(s) initialize your data object inputs on the platform
    # into dxpy.DXDataObject instances that you can start using immediately.

    bams = [dxpy.DXFile(item) for item in bams]

    # The following line(s) download your file inputs to the local file system
    # using variable names for the filenames.

    input_bam = ''
    ref = dxpy.describe({"$dnanexus_link": "file-GGVPZGj4fq4jpfZJP3YPBXZ7"})['name']
    for bam in bams:
        name = dxpy.describe(bam.get_id())['name']
        if name.endswith(".bam"): input_bam = name
        dxpy.download_dxfile(bam.get_id(), name)

    dxpy.download_dxfile({"$dnanexus_link": "file-GGVPZGj4fq4jpfZJP3YPBXZ7"}, ref)
    dxpy.download_dxfile({"$dnanexus_link": "file-GGZ90104fq4x6G1jKkF6Jz63"}, ref + ".fai")

    # create output file prefix
    sample = f"{family_number.strip().replace(" ", "")}_{sample_number.strip().replace(" ", "")}"

    # run manta shell script
    subprocess.run(["/home/dnanexus/run_manta.sh",
        input_bam,
        ref,
        sample
    ])

    # The following line fills in some basic dummy output and assumes
    # that you have created variables to represent your output with
    # the same name as your output fields.

    results = []
    for f in glob.glob('/home/dnanexus/out/*'):
        results.append(f)
    for f in glob.glob('/home/dnanexus/out/results/**/*', recursive=True):
        results.append(f)
    results = [dxpy.upload_local_file(f) for f in results if os.path.isfile(f)]

    output = {}
    output["results"] = [dxpy.dxlink(item) for item in results]

    return output

dxpy.run()
